apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce # 1つのノードから読み書きができる設定。
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard